// GENERATED by admin-kits/data/generate.mjs from dataset.json. Do not edit.
namespace NovusAdminKit.Data;

public record Kpi(string Value, string Label);
public record Signal(string Tone, string Eyebrow, string Headline, string Detail);
public record Transaction(string Id, string Ts, string Terminal, string Product, decimal Amount, string Currency, string Status);
public record Terminal(string Id, string Location, string Product, double Uptime, string Health, string LastSeen);

public static class SeedData
{
    public static readonly Kpi[] Kpis =
    {
        new("4.2M", "transactions today"),
        new("99.8%", "platform uptime"),
        new("312", "active terminals"),
        new("USD 18.4M", "settlement value"),
    };

    public static readonly Signal[] Signals =
    {
        new("danger", "Settlement risk", "2 failed settlements on TRM-0128", "Both failures in the last hour on the same terminal. Review the device before the next batch window."),
        new("warning", "Certificate", "Gateway certificate expires in 14 days", "Renew before 2026-09-10 to avoid an acceptance outage."),
    };

    public static readonly Transaction[] Transactions =
    {
        new("TXN-241099", "2026-08-27T18:31:00+08:00", "TRM-0177", "novapay", 151.17m, "USD", "settled"),
        new("TXN-241086", "2026-08-27T18:14:00+08:00", "TRM-0170", "novapay", 721.23m, "USD", "settled"),
        new("TXN-241073", "2026-08-27T17:57:00+08:00", "TRM-0163", "novastore", 401.87m, "USD", "pending"),
        new("TXN-241060", "2026-08-27T17:40:00+08:00", "TRM-0156", "novabank", 119.22m, "USD", "settled"),
        new("TXN-241047", "2026-08-27T16:23:00+08:00", "TRM-0149", "novapay", 931.32m, "USD", "settled"),
        new("TXN-241034", "2026-08-27T16:06:00+08:00", "TRM-0142", "novapay", 279.24m, "USD", "pending"),
        new("TXN-241021", "2026-08-27T15:49:00+08:00", "TRM-0135", "novapay", 695.14m, "USD", "failed"),
        new("TXN-241008", "2026-08-27T15:32:00+08:00", "TRM-0128", "novastore", 832.38m, "USD", "settled"),
        new("TXN-240982", "2026-08-27T14:58:00+08:00", "TRM-0114", "novapay", 549.11m, "USD", "pending"),
        new("TXN-240995", "2026-08-27T14:15:00+08:00", "TRM-0121", "novabank", 502.74m, "USD", "settled"),
        new("TXN-240969", "2026-08-27T13:41:00+08:00", "TRM-0107", "novapay", 237.94m, "USD", "settled"),
        new("TXN-240956", "2026-08-27T13:24:00+08:00", "TRM-0100", "novapay", 666.45m, "USD", "settled"),
        new("TXN-240930", "2026-08-27T12:50:00+08:00", "TRM-0170", "novapay", 290.38m, "USD", "settled"),
        new("TXN-240943", "2026-08-27T12:07:00+08:00", "TRM-0177", "novapay", 756.31m, "USD", "settled"),
        new("TXN-240917", "2026-08-27T11:33:00+08:00", "TRM-0163", "novastore", 434.90m, "USD", "settled"),
        new("TXN-240904", "2026-08-27T11:16:00+08:00", "TRM-0156", "novabank", 559.60m, "USD", "settled"),
        new("TXN-240891", "2026-08-27T10:59:00+08:00", "TRM-0149", "novapay", 303.93m, "USD", "settled"),
        new("TXN-240878", "2026-08-27T10:42:00+08:00", "TRM-0142", "novapay", 410.79m, "USD", "settled"),
        new("TXN-240865", "2026-08-27T09:25:00+08:00", "TRM-0135", "novapay", 648.94m, "USD", "settled"),
        new("TXN-240852", "2026-08-27T09:08:00+08:00", "TRM-0128", "novastore", 202.01m, "USD", "settled"),
        new("TXN-240839", "2026-08-27T08:51:00+08:00", "TRM-0121", "novabank", 64.14m, "USD", "pending"),
        new("TXN-240826", "2026-08-27T08:34:00+08:00", "TRM-0114", "novapay", 67.15m, "USD", "failed"),
        new("TXN-240813", "2026-08-27T07:17:00+08:00", "TRM-0107", "novapay", 523.98m, "USD", "settled"),
        new("TXN-240800", "2026-08-27T07:00:00+08:00", "TRM-0100", "novapay", 358.80m, "USD", "settled"),
    };

    public static readonly Terminal[] Terminals =
    {
        new("TRM-0100", "Makati flagship", "novapay", 99.5, "healthy", "2026-08-27T06:00:00+08:00"),
        new("TRM-0107", "Cebu IT Park", "novapay", 99.3, "healthy", "2026-08-27T07:11:00+08:00"),
        new("TRM-0114", "Quezon Ave", "novapay", 99.7, "healthy", "2026-08-27T08:22:00+08:00"),
        new("TRM-0121", "Colombo Fort", "novabank", 99.3, "healthy", "2026-08-27T09:33:00+08:00"),
        new("TRM-0128", "Kandy City Centre", "novastore", 96.4, "degraded", "2026-08-27T10:44:00+08:00"),
        new("TRM-0135", "Jakarta Sudirman", "novapay", 99.5, "healthy", "2026-08-27T11:55:00+08:00"),
        new("TRM-0142", "Bandung Dago", "novapay", 99.2, "healthy", "2026-08-27T12:06:00+08:00"),
        new("TRM-0149", "Phnom Penh Central", "novapay", 99.6, "healthy", "2026-08-27T13:17:00+08:00"),
        new("TRM-0156", "Gaborone Main Mall", "novabank", 99.2, "healthy", "2026-08-27T14:28:00+08:00"),
        new("TRM-0163", "Singapore Raffles", "novastore", 0, "offline", "2026-08-27T15:39:00+08:00"),
        new("TRM-0170", "Penang Georgetown", "novapay", 99.3, "healthy", "2026-08-27T16:50:00+08:00"),
        new("TRM-0177", "Davao Abreeza", "novapay", 99.3, "healthy", "2026-08-27T17:01:00+08:00"),
    };
}
