import "novus-design-kit/js/novus-theme.js";
import "./admin.css";
import "@material/web/button/filled-button.js";
import "@material/web/button/outlined-button.js";
import "@material/web/textfield/outlined-text-field.js";
import "@material/web/textfield/filled-text-field.js";
import "@material/web/checkbox/checkbox.js";
import "./novus-admin.js";
import "./console-pages.js";
