<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="10.0.11" />
  </ItemGroup>

  <Target Name="CopyNovusKit" BeforeTargets="PrepareForBuild">
    <ItemGroup>
      <NovusKit Include="node_modules/novus-design-kit/**/*" />
      <ChartJs Include="node_modules/chart.js/dist/chart.umd.js" />
    </ItemGroup>
    <Copy SourceFiles="@(NovusKit)" DestinationFiles="@(NovusKit->'wwwroot/lib/novus-design-kit/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(ChartJs)" DestinationFiles="@(ChartJs->'wwwroot/lib/chartjs/%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
